<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Histori extends CI_Controller
{


    function __construct()
    {
        parent::__construct();
        if (!$this->ion_auth->logged_in()) {
            redirect('auth');
        }
        $this->load->model('Histori_model');
        $this->load->library('form_validation');
        $this->user = $this->ion_auth->user()->row();
    }

    public function index()
    {
        $user = $this->user;
        $terparkir = $this->Histori_model->get_status_query();
        $histori = $this->Histori_model->get_all_query();
        $jumlah = $this->Histori_model->jumlah();
        
        $data = array(
            'terparkir_data' => $terparkir,
            'histori_data' => $histori,
            'jumlah' => $jumlah,
            'user' => $user, 'users'     => $this->ion_auth->user()->row(),

        );

        $this->template->load('template', 'histori_list', $data);
    }
}

/* End of file Histori.php */
/* Location: ./application/controllers/Histori.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-03 13:03:02 */
/* http://harviacode.com */
