<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dashboard_model extends CI_Model
{

    public $table = 'kendaraan';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }


    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }


    function total_rows($q = NULL) {
        $this->db->like('id', $q);
        $this->db->like('nama_civitas', $q);
        $this->db->like('status_civitas', $q);
        $this->db->like('nip_nim', $q);
        $this->db->like('plat_nomor', $q);
        $this->db->like('jenis_kendaraan', $q);
        $this->db->like('merk', $q);
        $this->db->like('foto_stnk', $q);
      	$this->db->or_like('status_kendaraan', $q);
      	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->like('nama_civitas', $q);
        $this->db->like('status_civitas', $q);
        $this->db->like('nip_nim', $q);
        $this->db->like('plat_nomor', $q);
        $this->db->like('jenis_kendaraan', $q);
        $this->db->like('merk', $q);
        $this->db->like('foto_stnk', $q);
      	$this->db->or_like('status_kendaraan', $q);
	       $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

}

/* End of file Kendaraan_model.php */
/* Location: ./application/models/Kendaraan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-03-18 03:21:05 */
/* http://harviacode.com */
